### ISSUE TITLE
Are there any plans on getting grab-site into the official Debian/Ubuntu software repositories?  

### ISSUE THREAD

**Issue by github-userx** [ArchiveTeam/grab-site#141]

**Comment by ivan** [comment]
It is gnerally the developers of those operating systems who are responsible for packaging things. Ubuntu mostly just pulls packages from Debian, so something being packaged in Debian would make it available to both. Anyone can request that something be packaged for Debian using the https://wiki.debian.org/RFP process - here are some sample requests: https://www.debian.org/devel/wnpp/requested

If someone is sufficiently motivated, I think they can [develop the packaging](https://wiki.debian.org/HowToPackageForDebian) and mention it in the bug instead of waiting for a Debian Developer to write it.
