### ISSUE TITLE
Continuing or updating a grab

### ISSUE THREAD

**Issue by nihelmasell** [ArchiveTeam/grab-site#153]
Hi, is there a way to continue or update a warc capture? I've been trying your program, but with big sites, sometimes my connection is lost, so I have to start over and over again. (it would also be great to just update captures, as with big sites *50-100 gb* subsequent captures take lots of space). Best regards

**Comment by ivan** [comment]
There's to way to continue or update, but for requests that fail to connect, the request will later be retried (note it can take a while because it goes to the end of the queue). The default is 3 tries but you can increase it. Also, if you notice your connection is down, you can pause all grab-site processes with `killall -STOP grab-site` and later `killall -CONT grab-site` to resume.

**Comment by ivan** [comment]
Leaving issue #58 for resuming a grab

**Comment by baznikin** [comment]
Hi, Ivan!

Great software, just spotted it yesterday. Sorry for "necro-issing', but as far as I notice wpull supports resuming internally - https://wpull.readthedocs.io/en/master/usage.html#stopping-resuming
Any chances to implement it?

However, I am more interested in archive updating. Could you suggest how to do it?

**Comment by TheTechRobo** [comment]
#58 for resuming

**Comment by baznikin** [comment]
> #58 for resuming

Thanks, just found it myself, wanted to remove my comment. Maybe it worth to put some info regarding resuming in FAQ.

But what about updating of previous archive, is it possible?
